language: objective-c
osx_image: xcode7.2
bundler_args: --without development --deployment --jobs=3 --retry=3
cache: bundler

before_install:
  - export LANG=en_US.UTF-8

script:
  - rake test

notifications:
  email:
    recipients:
      - john.watson@raizlabs.com
    on_success: change
    on_failure: always
